version: "3.9"

services:
  api:
    build: .
    container_name: crime-risk-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENABLE_CACHE=true

  redis:
    image: redis:7-alpine
    container_name: crime-risk-redis
    ports:
      - "6379:6379"